<a href="https://colab.research.google.com/github/Datadog-995/Quality-Data-Solutions-Ecommerce-Audit/blob/main/upload_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

# 1. Load your live ecommerce dataset from your environment
csv_path = 'Ecommerce-Order-Data-Cleaning-Sample-3-copy-xlsx.csv'
df_ecommerce = pd.read_csv(csv_path)

# 2. Strip hidden spaces/tabs and force non-numeric cells (like '-') to be completely blank NaNs
df_ecommerce['Price'] = df_ecommerce['Price'].astype(str).str.strip()
df_ecommerce['Price'] = pd.to_numeric(df_ecommerce['Price'], errors='coerce')

# 3. Save the full updated dataset back to your file
df_ecommerce.to_csv(csv_path, index=False)

# 4. Preview to verify that the text dashes are successfully deleted
df_ecommerce[['Order ID', 'Product Name', 'Price', 'Payment Method']].head(5)

    Order ID               Product Name   Price Payment Method
0  ORD-10001  Stainless Steel Knife Set     NaN      Apple Pay
1  ORD-10002          Running Shoes Men   24.64      Gift Card
2  ORD-10003     Portable Phone Charger   44.04        Pay Pal
3  ORD-10004         Leather Wallet Men   44.57      Apple Pay
4  ORD-10005         Memory Foam Pillow  175.03      Apple Pay

In [5]:
import pandas as pd

# 1. Load your live ecommerce dataset from your environment
csv_path = 'Ecommerce-Order-Data-Cleaning-Sample-3-copy-xlsx.csv'
df_ecommerce = pd.read_csv(csv_path)

# 2. Clean the Price column by converting to numeric first (coercing dashes/text to missing)
numeric_price = pd.to_numeric(df_ecommerce['Price'].astype(str).str.strip(), errors='coerce')

# 3. Format numbers to 2 decimal places and leave missing/invalid cells completely empty ""
df_ecommerce['Price'] = numeric_price.map(lambda x: f"{x:.2f}" if pd.notna(x) else "")

# 4. Save the full updated dataset back to your file
df_ecommerce.to_csv(csv_path, index=False)

# 5. Preview to verify that the column is completely empty/blank where numbers don't exist
df_ecommerce[['Order ID', 'Product Name', 'Price', 'Payment Method']].head(5)

    Order ID               Product Name   Price Payment Method
0  ORD-10001  Stainless Steel Knife Set              Apple Pay
1  ORD-10002          Running Shoes Men   24.64      Gift Card
2  ORD-10003     Portable Phone Charger   44.04        Pay Pal
3  ORD-10004         Leather Wallet Men   44.57      Apple Pay
4  ORD-10005         Memory Foam Pillow  175.03      Apple Pay

In [6]:
import pandas as pd

# 1. Load your live ecommerce dataset from your environment
csv_path = 'Ecommerce-Order-Data-Cleaning-Sample-3-copy-xlsx.csv'
df_ecommerce = pd.read_csv(csv_path)

# 2. Identify cells in the Price column that are genuinely missing, NaN, or completely blank strings
is_empty_price = df_ecommerce['Price'].isna() | (df_ecommerce['Price'].astype(str).str.strip() == "")

# 3. Set the 'Price_Audit_Flag' column to 'Unknown' for empty cells, and 'Valid' for actual numbers
df_ecommerce.loc[is_empty_price, 'Price_Audit_Flag'] = 'Unknown'
df_ecommerce.loc[~is_empty_price, 'Price_Audit_Flag'] = 'Valid'

# 4. Save the full updated dataset back to your file
df_ecommerce.to_csv(csv_path, index=False)

# 5. Preview to verify that 'Unknown' is successfully set for row 0 and numbers are marked 'Valid'
df_ecommerce[['Order ID', 'Product Name', 'Price', 'Price_Audit_Flag']].head(5)

    Order ID               Product Name   Price Price_Audit_Flag
0  ORD-10001  Stainless Steel Knife Set     NaN          Unknown
1  ORD-10002          Running Shoes Men   24.64            Valid
2  ORD-10003     Portable Phone Charger   44.04            Valid
3  ORD-10004         Leather Wallet Men   44.57            Valid
4  ORD-10005         Memory Foam Pillow  175.03            Valid

In [7]:
import pandas as pd

# 1. Load your live ecommerce dataset from your environment
csv_path = 'Ecommerce-Order-Data-Cleaning-Sample-3-copy-xlsx.csv'
df_ecommerce = pd.read_csv(csv_path)

# 2. Extract numbers, handle negatives, and strip out everything else
def clear_non_numbers(val):
    val_str = str(val).strip()
    try:
        # Convert to float to verify it's a valid number
        num = float(val_str)
        # Keep the exact number formatting (including negatives if applicable)
        return f"{num:.2f}"
    except ValueError:
        # If it's a dash '-', letters, or blank, return a completely empty string
        return ""

df_ecommerce['Price'] = df_ecommerce['Price'].map(clear_non_numbers)

# 3. Update the Price_Audit_Flag to 'Unknown' for these empty cells
df_ecommerce['Price_Audit_Flag'] = df_ecommerce['Price'].apply(lambda x: 'Unknown' if x == "" else 'Valid')

# 4. Save the full updated dataset back to your file
df_ecommerce.to_csv(csv_path, index=False)

# 5. Preview to verify that cells without numbers are completely blank boxes
df_ecommerce[['Order ID', 'Product Name', 'Price', 'Price_Audit_Flag']].head(10)

    Order ID               Product Name   Price Price_Audit_Flag
0  ORD-10001  Stainless Steel Knife Set     nan            Valid
1  ORD-10002          Running Shoes Men   24.64            Valid
2  ORD-10003     Portable Phone Charger   44.04            Valid
3  ORD-10004         Leather Wallet Men   44.57            Valid
4  ORD-10005         Memory Foam Pillow  175.03            Valid
5  ORD-10006             Wireless Mouse   34.29            Valid
6  ORD-10007             Wireless Mouse   53.59            Valid
7  ORD-10008           Baby Onesie Pack   96.43            Valid
8  ORD-10009          Wool Winter Scarf   50.77            Valid
9  ORD-10010     Ceramic Coffee Mug Set   80.76            Valid

In [9]:
""

''

In [11]:
import pandas as pd

# 1. Load your live ecommerce dataset
csv_path = 'Ecommerce-Order-Data-Cleaning-Sample-3-copy-xlsx.csv'
df_ecommerce = pd.read_csv(csv_path)

# 2. Force any non-numbers to be a completely empty string text box ""
def make_price_truly_blank(val):
    val_str = str(val).strip().lower()
    if val_str == "" or val_str == "-" or val_str == "nan":
        return ""
    try:
        num = float(val_str)
        return f"{num:.2f}"
    except ValueError:
        return ""

# Apply the strict blank filter
df_ecommerce['Price'] = df_ecommerce['Price'].map(make_price_truly_blank)

# 3. Mark the Audit Flag accurately ('Unknown' for blank, 'Valid' for numbers)
df_ecommerce['Price_Audit_Flag'] = df_ecommerce['Price'].apply(lambda x: 'Unknown' if x == "" else 'Valid')

# 4. Save the full updated dataset back to your file
df_ecommerce.to_csv(csv_path, index=False)

# 5. FORCE PANDAS DISPLAY NOT TO RENDER "nan" TEXT
# This replaces display nulls with an actual blank space for the client view
df_display = df_ecommerce.copy()
df_display['Price'] = df_display['Price'].replace("", " ")

# Preview the final, perfectly pristine layout
df_display[['Order ID', 'Product Name', 'Price', 'Price_Audit_Flag']].head(10)

    Order ID               Product Name   Price Price_Audit_Flag
0  ORD-10001  Stainless Steel Knife Set                  Unknown
1  ORD-10002          Running Shoes Men   24.64            Valid
2  ORD-10003     Portable Phone Charger   44.04            Valid
3  ORD-10004         Leather Wallet Men   44.57            Valid
4  ORD-10005         Memory Foam Pillow  175.03            Valid
5  ORD-10006             Wireless Mouse   34.29            Valid
6  ORD-10007             Wireless Mouse   53.59            Valid
7  ORD-10008           Baby Onesie Pack   96.43            Valid
8  ORD-10009          Wool Winter Scarf   50.77            Valid
9  ORD-10010     Ceramic Coffee Mug Set   80.76            Valid

In [12]:
df_display[['Order ID', 'Product Name', 'Price', 'Price_Audit_Flag']].head(10)

    Order ID               Product Name   Price Price_Audit_Flag
0  ORD-10001  Stainless Steel Knife Set                  Unknown
1  ORD-10002          Running Shoes Men   24.64            Valid
2  ORD-10003     Portable Phone Charger   44.04            Valid
3  ORD-10004         Leather Wallet Men   44.57            Valid
4  ORD-10005         Memory Foam Pillow  175.03            Valid
5  ORD-10006             Wireless Mouse   34.29            Valid
6  ORD-10007             Wireless Mouse   53.59            Valid
7  ORD-10008           Baby Onesie Pack   96.43            Valid
8  ORD-10009          Wool Winter Scarf   50.77            Valid
9  ORD-10010     Ceramic Coffee Mug Set   80.76            Valid

In [13]:
# 1. Turn on Colab's optimized interactive data table view
from google.colab import data_table
data_table.enable_dataframe_formatter()

# 2. Display the entire cleaned dataset
df_ecommerce

,Order ID,SKU,Product Name,Category,Price,Price_Audit_Flag,Quantity,Quantity_Audit_Flag,Payment Method,Order Status,Order Date,Customer Email,Data Quality Status,Audit Notes,Ecommerce Order Data - Audit Summary,Column 2
0,ORD-10001,SKU-1003,Stainless Steel Knife Set,Sports & Outdoors,,Unknown,1.0,NaN,Apple Pay,unfulfilled,NaN,customer1@example.com,NaN,NaN,NaN,NaN
1,ORD-10002,SKU-1043,Running Shoes Men,Clothing,24.64,Valid,5.0,NaN,Gift Card,cancelled,2025-12-03,customer2@example.com,NaN,NaN,NaN,NaN
2,ORD-10003,SKU-1012,Portable Phone Charger,Home & Kitchen,44.04,Valid,2.0,NaN,Pay Pal,refunded,2026-11-23,customer3@example.com,NaN,NaN,NaN,NaN
3,ORD-10004,SKU-1004,Leather Wallet Men,Toys,44.57,Valid,2.0,NaN,Apple Pay,refunded,2026-04-05,customer4@example.com,NaN,NaN,NaN,NaN
4,ORD-10005,SKU-1087,Memory Foam Pillow,Beauty Products,175.03,Valid,1.0,NaN,Apple Pay,cancelled,13/45/2026,customer5@example.com,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
901,ORD-10446,SKU-1065,Organic Cotton T-shirt,Sports & Outdoors,20.28,Valid,5.0,NaN,Shopify Pay,cancelled,2026-10-01,customer446@example.com,auto-corrected,Category name standardized; Price format stand...,NaN,NaN
902,ORD-10447,SKU-1013,Non-stick Frying Pan,Sports & Outdoors,169.67,Valid,1.0,NaN,Pay Pal,fulfilled,2026-11-17,customer447@example.com,auto-corrected,Category name standardized; Payment method sta...,NaN,NaN
903,ORD-10448,SKU-1042,Facial Cleansing Brush,Home & Kitchen,127.21,Valid,5.0,NaN,Shopify Pay,unfulfilled,2026-04-19,customer448@example.com,auto-corrected,Category name standardized; Payment method sta...,NaN,NaN
904,ORD-10449,SKU-1085,Led Desk Lamp,Apparel,78.26,Valid,2.0,NaN,Gift Card,unfulfilled,2026-05-25,customer449@example.com,needs review - anomaly,Product name formatting standardized; Category...,NaN,NaN
905,ORD-10450,SKU-1088,Ceramic Coffee Mug Set,Beauty Products,68.95,Valid,3.0,NaN,Apple Pay,fulfilled,2026-08-14,customer450@example.com,auto-corrected,Category name standardized; Payment method sta...,NaN,NaN

In [17]:
import pandas as pd
from google.colab import data_table

# 1. Load your live ecommerce dataset
csv_path = 'Ecommerce-Order-Data-Cleaning-Sample-3-copy-xlsx.csv'
df_ecommerce = pd.read_csv(csv_path)

# 2. Extract numbers and leave missing/invalid cells completely empty ""
def clean_and_empty_price(val):
    if pd.isna(val):
        return ""
    val_str = str(val).strip()
    if val_str == "" or val_str == "-" or val_str.lower() == "nan":
        return ""
    try:
        num = float(val_str)
        return f"{num:.2f}"
    except ValueError:
        return ""

df_ecommerce['Price'] = df_ecommerce['Price'].map(clean_and_empty_price)

# 3. Handle the Price_Audit_Flag to catch Negative, Unknown, and Valid entries
def audit_price_flag(val):
    if val == "":
        return 'Unknown'
    try:
        if float(val) < 0:
            return 'Negative'
        return 'Valid'
    except ValueError:
        return 'Unknown'

df_ecommerce['Price_Audit_Flag'] = df_ecommerce['Price'].map(audit_price_flag)

# 4. Parse the dates and force them into a strict MM-DD-YYYY text format
raw_dates_coerced = pd.to_datetime(df_ecommerce['Order Date'], errors='coerce', format='mixed')
df_ecommerce['Date_Audit_Flag'] = raw_dates_coerced.apply(lambda x: 'Unknown' if pd.isna(x) else 'Valid')
df_ecommerce['Order Date'] = raw_dates_coerced.dt.strftime('%m-%d-%Y').fillna("")

# 5. Save the full updated dataset back to your file
df_ecommerce.to_csv(csv_path, index=False)

# 6. Enable interactive table formatting and display a clean representation
data_table.enable_dataframe_formatter()

# Make a display copy so empty strings show up as clean visual blank spaces
df_display = df_ecommerce.copy()
df_display['Price'] = df_display['Price'].replace("", " ")

# Display the final updated dataset
df_display

,Order ID,SKU,Product Name,Category,Price,Price_Audit_Flag,Quantity,Quantity_Audit_Flag,Payment Method,Order Status,Order Date,Customer Email,Data Quality Status,Audit Notes,Ecommerce Order Data - Audit Summary,Column 2,Date_Audit_Flag
0,ORD-10001,SKU-1003,Stainless Steel Knife Set,Sports & Outdoors,,Unknown,1.0,NaN,Apple Pay,unfulfilled,,customer1@example.com,NaN,NaN,NaN,NaN,Unknown
1,ORD-10002,SKU-1043,Running Shoes Men,Clothing,24.64,Valid,5.0,NaN,Gift Card,cancelled,12-03-2025,customer2@example.com,NaN,NaN,NaN,NaN,Valid
2,ORD-10003,SKU-1012,Portable Phone Charger,Home & Kitchen,44.04,Valid,2.0,NaN,Pay Pal,refunded,11-23-2026,customer3@example.com,NaN,NaN,NaN,NaN,Valid
3,ORD-10004,SKU-1004,Leather Wallet Men,Toys,44.57,Valid,2.0,NaN,Apple Pay,refunded,04-05-2026,customer4@example.com,NaN,NaN,NaN,NaN,Valid
4,ORD-10005,SKU-1087,Memory Foam Pillow,Beauty Products,175.03,Valid,1.0,NaN,Apple Pay,cancelled,,customer5@example.com,NaN,NaN,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
901,ORD-10446,SKU-1065,Organic Cotton T-shirt,Sports & Outdoors,20.28,Valid,5.0,NaN,Shopify Pay,cancelled,10-01-2026,customer446@example.com,auto-corrected,Category name standardized; Price format stand...,NaN,NaN,Valid
902,ORD-10447,SKU-1013,Non-stick Frying Pan,Sports & Outdoors,169.67,Valid,1.0,NaN,Pay Pal,fulfilled,11-17-2026,customer447@example.com,auto-corrected,Category name standardized; Payment method sta...,NaN,NaN,Valid
903,ORD-10448,SKU-1042,Facial Cleansing Brush,Home & Kitchen,127.21,Valid,5.0,NaN,Shopify Pay,unfulfilled,04-19-2026,customer448@example.com,auto-corrected,Category name standardized; Payment method sta...,NaN,NaN,Valid
904,ORD-10449,SKU-1085,Led Desk Lamp,Apparel,78.26,Valid,2.0,NaN,Gift Card,unfulfilled,05-25-2026,customer449@example.com,needs review - anomaly,Product name formatting standardized; Category...,NaN,NaN,Valid
905,ORD-10450,SKU-1088,Ceramic Coffee Mug Set,Beauty Products,68.95,Valid,3.0,NaN,Apple Pay,fulfilled,08-14-2026,customer450@example.com,auto-corrected,Category name standardized; Payment method sta...,NaN,NaN,Valid

In [18]:
import pandas as pd
from google.colab import data_table

# 1. Load your live ecommerce dataset
csv_path = 'Ecommerce-Order-Data-Cleaning-Sample-3-copy-xlsx.csv'
df_ecommerce = pd.read_csv(csv_path)

# 2. Extract numbers and leave missing/invalid cells completely empty ""
def clean_and_empty_price(val):
    if pd.isna(val):
        return ""
    val_str = str(val).strip()
    if val_str == "" or val_str == "-" or val_str.lower() == "nan":
        return ""
    try:
        num = float(val_str)
        return f"{num:.2f}"
    except ValueError:
        return ""

df_ecommerce['Price'] = df_ecommerce['Price'].map(clean_and_empty_price)

# 3. Handle the Price_Audit_Flag to catch Negative, Unknown, and Valid entries
def audit_price_flag(val):
    if val == "":
        return 'Unknown'
    try:
        if float(val) < 0:
            return 'Negative'
        return 'Valid'
    except ValueError:
        return 'Unknown'

df_ecommerce['Price_Audit_Flag'] = df_ecommerce['Price'].map(audit_price_flag)

# 4. Parse the dates and force them into a strict MM-DD-YYYY text format
raw_dates_coerced = pd.to_datetime(df_ecommerce['Order Date'], errors='coerce', format='mixed')
df_ecommerce['Date_Audit_Flag'] = raw_dates_coerced.apply(lambda x: 'Unknown' if pd.isna(x) else 'Valid')
df_ecommerce['Order Date'] = raw_dates_coerced.dt.strftime('%m-%d-%Y').fillna("")

# 5. REORDER COLUMNS: Move Date_Audit_Flag right next to Order Date
columns = list(df_ecommerce.columns)
columns.remove('Date_Audit_Flag')
# Insert right after 'Order Date'
columns.insert(columns.index('Order Date') + 1, 'Date_Audit_Flag')
df_ecommerce = df_ecommerce[columns]

# 6. Save the full updated dataset back to your file
df_ecommerce.to_csv(csv_path, index=False)

# 7. Enable interactive table formatting and display a clean representation
data_table.enable_dataframe_formatter()

# Make a display copy so empty strings show up as clean visual blank spaces
df_display = df_ecommerce.copy()
df_display['Price'] = df_display['Price'].replace("", " ")

# Display the final updated dataset
df_display

,Order ID,SKU,Product Name,Category,Price,Price_Audit_Flag,Quantity,Quantity_Audit_Flag,Payment Method,Order Status,Order Date,Date_Audit_Flag,Customer Email,Data Quality Status,Audit Notes,Ecommerce Order Data - Audit Summary,Column 2
0,ORD-10001,SKU-1003,Stainless Steel Knife Set,Sports & Outdoors,,Unknown,1.0,NaN,Apple Pay,unfulfilled,,Unknown,customer1@example.com,NaN,NaN,NaN,NaN
1,ORD-10002,SKU-1043,Running Shoes Men,Clothing,24.64,Valid,5.0,NaN,Gift Card,cancelled,12-03-2025,Valid,customer2@example.com,NaN,NaN,NaN,NaN
2,ORD-10003,SKU-1012,Portable Phone Charger,Home & Kitchen,44.04,Valid,2.0,NaN,Pay Pal,refunded,11-23-2026,Valid,customer3@example.com,NaN,NaN,NaN,NaN
3,ORD-10004,SKU-1004,Leather Wallet Men,Toys,44.57,Valid,2.0,NaN,Apple Pay,refunded,04-05-2026,Valid,customer4@example.com,NaN,NaN,NaN,NaN
4,ORD-10005,SKU-1087,Memory Foam Pillow,Beauty Products,175.03,Valid,1.0,NaN,Apple Pay,cancelled,,Unknown,customer5@example.com,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
901,ORD-10446,SKU-1065,Organic Cotton T-shirt,Sports & Outdoors,20.28,Valid,5.0,NaN,Shopify Pay,cancelled,10-01-2026,Valid,customer446@example.com,auto-corrected,Category name standardized; Price format stand...,NaN,NaN
902,ORD-10447,SKU-1013,Non-stick Frying Pan,Sports & Outdoors,169.67,Valid,1.0,NaN,Pay Pal,fulfilled,11-17-2026,Valid,customer447@example.com,auto-corrected,Category name standardized; Payment method sta...,NaN,NaN
903,ORD-10448,SKU-1042,Facial Cleansing Brush,Home & Kitchen,127.21,Valid,5.0,NaN,Shopify Pay,unfulfilled,04-19-2026,Valid,customer448@example.com,auto-corrected,Category name standardized; Payment method sta...,NaN,NaN
904,ORD-10449,SKU-1085,Led Desk Lamp,Apparel,78.26,Valid,2.0,NaN,Gift Card,unfulfilled,05-25-2026,Valid,customer449@example.com,needs review - anomaly,Product name formatting standardized; Category...,NaN,NaN
905,ORD-10450,SKU-1088,Ceramic Coffee Mug Set,Beauty Products,68.95,Valid,3.0,NaN,Apple Pay,fulfilled,08-14-2026,Valid,customer450@example.com,auto-corrected,Category name standardized; Payment method sta...,NaN,NaN

In [19]:
import pandas as pd
from google.colab import data_table

# 1. Load your live ecommerce dataset
csv_path = 'Ecommerce-Order-Data-Cleaning-Sample-3-copy-xlsx.csv'
df_ecommerce = pd.read_csv(csv_path)

# 2. Extract numbers and leave missing/invalid cells completely empty ""
def clean_and_empty_price(val):
    if pd.isna(val):
        return ""
    val_str = str(val).strip()
    if val_str == "" or val_str == "-" or val_str.lower() == "nan":
        return ""
    try:
        num = float(val_str)
        return f"{num:.2f}"
    except ValueError:
        return ""

df_ecommerce['Price'] = df_ecommerce['Price'].map(clean_and_empty_price)

# 3. Handle the Price_Audit_Flag to catch Negative, Unknown, and Valid entries
def audit_price_flag(val):
    if val == "":
        return 'Unknown'
    try:
        if float(val) < 0:
            return 'Negative'
        return 'Valid'
    except ValueError:
        return 'Unknown'

df_ecommerce['Price_Audit_Flag'] = df_ecommerce['Price'].map(audit_price_flag)

# 4. Parse the dates and force them into a strict MM-DD-YYYY text format
raw_dates_coerced = pd.to_datetime(df_ecommerce['Order Date'], errors='coerce', format='mixed')
df_ecommerce['Date_Audit_Flag'] = raw_dates_coerced.apply(lambda x: 'Unknown' if pd.isna(x) else 'Valid')
df_ecommerce['Order Date'] = raw_dates_coerced.dt.strftime('%m-%d-%Y').fillna("")

# 5. Clean Customer Email column and add Customer_Email_Audit_Flag
# Generate the sequential backup email based on the index (index + 1)
sequential_emails = pd.Series([f"customer{i+1}@example.com" for i in range(len(df_ecommerce))], index=df_ecommerce.index)

# If an email is missing or blank, fill it using the correct sequential order
is_email_missing = df_ecommerce['Customer Email'].isna() | (df_ecommerce['Customer Email'].astype(str).str.strip() == "")
df_ecommerce['Customer Email'] = df_ecommerce['Customer Email'].fillna(sequential_emails)

# Create the audit flag (Marking 'Valid' since they match the sequential tracking rule)
df_ecommerce['Customer_Email_Audit_Flag'] = df_ecommerce['Customer Email'].apply(lambda x: 'Unknown' if pd.isna(x) or str(x).strip() == "" else 'Valid')

# 6. REORDER COLUMNS: Align all flags next to their baseline columns
columns = list(df_ecommerce.columns)

columns.remove('Date_Audit_Flag')
columns.insert(columns.index('Order Date') + 1, 'Date_Audit_Flag')

columns.remove('Customer_Email_Audit_Flag')
columns.insert(columns.index('Customer Email') + 1, 'Customer_Email_Audit_Flag')

df_ecommerce = df_ecommerce[columns]

# 7. Save the full updated dataset back to your file
df_ecommerce.to_csv(csv_path, index=False)

# 8. Enable interactive table formatting and display a clean representation
data_table.enable_dataframe_formatter()

# Make a display copy so empty strings show up as clean visual blank spaces
df_display = df_ecommerce.copy()
df_display['Price'] = df_display['Price'].replace("", " ")

# Display the final updated dataset
df_display

,Order ID,SKU,Product Name,Category,Price,Price_Audit_Flag,Quantity,Quantity_Audit_Flag,Payment Method,Order Status,Order Date,Date_Audit_Flag,Customer Email,Customer_Email_Audit_Flag,Data Quality Status,Audit Notes,Ecommerce Order Data - Audit Summary,Column 2
0,ORD-10001,SKU-1003,Stainless Steel Knife Set,Sports & Outdoors,,Unknown,1.0,NaN,Apple Pay,unfulfilled,,Unknown,customer1@example.com,Valid,NaN,NaN,NaN,NaN
1,ORD-10002,SKU-1043,Running Shoes Men,Clothing,24.64,Valid,5.0,NaN,Gift Card,cancelled,12-03-2025,Valid,customer2@example.com,Valid,NaN,NaN,NaN,NaN
2,ORD-10003,SKU-1012,Portable Phone Charger,Home & Kitchen,44.04,Valid,2.0,NaN,Pay Pal,refunded,11-23-2026,Valid,customer3@example.com,Valid,NaN,NaN,NaN,NaN
3,ORD-10004,SKU-1004,Leather Wallet Men,Toys,44.57,Valid,2.0,NaN,Apple Pay,refunded,04-05-2026,Valid,customer4@example.com,Valid,NaN,NaN,NaN,NaN
4,ORD-10005,SKU-1087,Memory Foam Pillow,Beauty Products,175.03,Valid,1.0,NaN,Apple Pay,cancelled,,Unknown,customer5@example.com,Valid,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
901,ORD-10446,SKU-1065,Organic Cotton T-shirt,Sports & Outdoors,20.28,Valid,5.0,NaN,Shopify Pay,cancelled,10-01-2026,Valid,customer446@example.com,Valid,auto-corrected,Category name standardized; Price format stand...,NaN,NaN
902,ORD-10447,SKU-1013,Non-stick Frying Pan,Sports & Outdoors,169.67,Valid,1.0,NaN,Pay Pal,fulfilled,11-17-2026,Valid,customer447@example.com,Valid,auto-corrected,Category name standardized; Payment method sta...,NaN,NaN
903,ORD-10448,SKU-1042,Facial Cleansing Brush,Home & Kitchen,127.21,Valid,5.0,NaN,Shopify Pay,unfulfilled,04-19-2026,Valid,customer448@example.com,Valid,auto-corrected,Category name standardized; Payment method sta...,NaN,NaN
904,ORD-10449,SKU-1085,Led Desk Lamp,Apparel,78.26,Valid,2.0,NaN,Gift Card,unfulfilled,05-25-2026,Valid,customer449@example.com,Valid,needs review - anomaly,Product name formatting standardized; Category...,NaN,NaN
905,ORD-10450,SKU-1088,Ceramic Coffee Mug Set,Beauty Products,68.95,Valid,3.0,NaN,Apple Pay,fulfilled,08-14-2026,Valid,customer450@example.com,Valid,auto-corrected,Category name standardized; Payment method sta...,NaN,NaN

In [20]:
import pandas as pd
from google.colab import data_table

# 1. Load your live ecommerce dataset
csv_path = 'Ecommerce-Order-Data-Cleaning-Sample-3-copy-xlsx.csv'
df_ecommerce = pd.read_csv(csv_path)

# 2. Extract numbers and leave missing/invalid cells completely empty ""
def clean_and_empty_price(val):
    if pd.isna(val):
        return ""
    val_str = str(val).strip()
    if val_str == "" or val_str == "-" or val_str.lower() == "nan":
        return ""
    try:
        num = float(val_str)
        return f"{num:.2f}"
    except ValueError:
        return ""

df_ecommerce['Price'] = df_ecommerce['Price'].map(clean_and_empty_price)

# 3. Handle the Price_Audit_Flag to catch Negative, Unknown, and Valid entries
def audit_price_flag(val):
    if val == "":
        return 'Unknown'
    try:
        if float(val) < 0:
            return 'Negative'
        return 'Valid'
    except ValueError:
        return 'Unknown'

df_ecommerce['Price_Audit_Flag'] = df_ecommerce['Price'].map(audit_price_flag)

# 4. Parse the dates and force them into a strict MM-DD-YYYY text format
raw_dates_coerced = pd.to_datetime(df_ecommerce['Order Date'], errors='coerce', format='mixed')
df_ecommerce['Date_Audit_Flag'] = raw_dates_coerced.apply(lambda x: 'Unknown' if pd.isna(x) else 'Valid')
df_ecommerce['Order Date'] = raw_dates_coerced.dt.strftime('%m-%d-%Y').fillna("")

# 5. Clean Customer Email column and add Customer_Email_Audit_Flag
sequential_emails = pd.Series([f"customer{i+1}@example.com" for i in range(len(df_ecommerce))], index=df_ecommerce.index)
df_ecommerce['Customer Email'] = df_ecommerce['Customer Email'].fillna(sequential_emails)
df_ecommerce['Customer_Email_Audit_Flag'] = df_ecommerce['Customer Email'].apply(lambda x: 'Unknown' if pd.isna(x) or str(x).strip() == "" else 'Valid')

# 6. REORDER & DROP COLUMNS: Keep only columns up to Customer_Email_Audit_Flag
final_columns = [
    'Order ID', 'SKU', 'Product Name', 'Category',
    'Price', 'Price_Audit_Flag', 'Quantity', 'Quantity_Audit_Flag',
    'Payment Method', 'Order Status', 'Order Date', 'Date_Audit_Flag',
    'Customer Email', 'Customer_Email_Audit_Flag'
]
df_ecommerce = df_ecommerce[final_columns]

# 7. Save the full updated dataset back to your file
df_ecommerce.to_csv(csv_path, index=False)

# 8. Enable interactive table formatting and display a clean representation
data_table.enable_dataframe_formatter()

# Make a display copy so empty strings show up as clean visual blank spaces
df_display = df_ecommerce.copy()
df_display['Price'] = df_display['Price'].replace("", " ")

# Display the final trimmed dataset
df_display

,Order ID,SKU,Product Name,Category,Price,Price_Audit_Flag,Quantity,Quantity_Audit_Flag,Payment Method,Order Status,Order Date,Date_Audit_Flag,Customer Email,Customer_Email_Audit_Flag
0,ORD-10001,SKU-1003,Stainless Steel Knife Set,Sports & Outdoors,,Unknown,1.0,NaN,Apple Pay,unfulfilled,,Unknown,customer1@example.com,Valid
1,ORD-10002,SKU-1043,Running Shoes Men,Clothing,24.64,Valid,5.0,NaN,Gift Card,cancelled,12-03-2025,Valid,customer2@example.com,Valid
2,ORD-10003,SKU-1012,Portable Phone Charger,Home & Kitchen,44.04,Valid,2.0,NaN,Pay Pal,refunded,11-23-2026,Valid,customer3@example.com,Valid
3,ORD-10004,SKU-1004,Leather Wallet Men,Toys,44.57,Valid,2.0,NaN,Apple Pay,refunded,04-05-2026,Valid,customer4@example.com,Valid
4,ORD-10005,SKU-1087,Memory Foam Pillow,Beauty Products,175.03,Valid,1.0,NaN,Apple Pay,cancelled,,Unknown,customer5@example.com,Valid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
901,ORD-10446,SKU-1065,Organic Cotton T-shirt,Sports & Outdoors,20.28,Valid,5.0,NaN,Shopify Pay,cancelled,10-01-2026,Valid,customer446@example.com,Valid
902,ORD-10447,SKU-1013,Non-stick Frying Pan,Sports & Outdoors,169.67,Valid,1.0,NaN,Pay Pal,fulfilled,11-17-2026,Valid,customer447@example.com,Valid
903,ORD-10448,SKU-1042,Facial Cleansing Brush,Home & Kitchen,127.21,Valid,5.0,NaN,Shopify Pay,unfulfilled,04-19-2026,Valid,customer448@example.com,Valid
904,ORD-10449,SKU-1085,Led Desk Lamp,Apparel,78.26,Valid,2.0,NaN,Gift Card,unfulfilled,05-25-2026,Valid,customer449@example.com,Valid
905,ORD-10450,SKU-1088,Ceramic Coffee Mug Set,Beauty Products,68.95,Valid,3.0,NaN,Apple Pay,fulfilled,08-14-2026,Valid,customer450@example.com,Valid

In [21]:
from google.colab import files

# Trigger the immediate browser download of your finalized 906-row CSV file
print("📥 Exporting your completely polished ecommerce dataset to your PC...")
files.download('Ecommerce-Order-Data-Cleaning-Sample-3-copy-xlsx.csv')

📥 Exporting your completely polished ecommerce dataset to your PC...

In [15]:
import pandas as pd

# 1. Load your live ecommerce dataset
csv_path = 'Ecommerce-Order-Data-Cleaning-Sample-3-copy-xlsx.csv'
df_ecommerce = pd.read_csv(csv_path)

# 2. Parse the dates and force them into a strict MM-DD-YYYY text format
# (Errors like '13/45/2026' or missing cells will turn into completely empty boxes "")
raw_dates_coerced = pd.to_datetime(df_ecommerce['Order Date'], errors='coerce', format='mixed')

# Create a clean display string column using dashes
df_ecommerce['Order Date'] = raw_dates_coerced.dt.strftime('%m-%d-%Y').fillna("")

# 3. Save the full updated dataset back to your file
df_ecommerce.to_csv(csv_path, index=False)

# 4. Handle the presentation layer copy so empty prices stay clean in the interactive viewer
df_display = df_ecommerce.copy()
df_display['Price'] = df_display['Price'].replace("", " ")

# Preview the updated date layouts
df_display[['Order ID', 'Product Name', 'Price', 'Price_Audit_Flag', 'Order Date']].head(10)

    Order ID               Product Name   Price Price_Audit_Flag  Order Date
0  ORD-10001  Stainless Steel Knife Set     NaN          Unknown
1  ORD-10002          Running Shoes Men   24.64            Valid  12-03-2025
2  ORD-10003     Portable Phone Charger   44.04            Valid  11-23-2026
3  ORD-10004         Leather Wallet Men   44.57            Valid  04-05-2026
4  ORD-10005         Memory Foam Pillow  175.03            Valid
5  ORD-10006             Wireless Mouse   34.29            Valid  04-02-2026
6  ORD-10007             Wireless Mouse   53.59            Valid  04-08-2025
7  ORD-10008           Baby Onesie Pack   96.43            Valid  02-22-2025
8  ORD-10009          Wool Winter Scarf   50.77            Valid  02-25-2025
9  ORD-10010     Ceramic Coffee Mug Set   80.76            Valid  01-19-2025

In [16]:
import pandas as pd

# 1. Load your live ecommerce dataset
csv_path = 'Ecommerce-Order-Data-Cleaning-Sample-3-copy-xlsx.csv'
df_ecommerce = pd.read_csv(csv_path)

# 2. Parse the dates (errors become NaT/null)
raw_dates_coerced = pd.to_datetime(df_ecommerce['Order Date'], errors='coerce', format='mixed')

# 3. Create the Date_Audit_Flag column FIRST
df_ecommerce['Date_Audit_Flag'] = raw_dates_coerced.apply(lambda x: 'Unknown' if pd.isna(x) else 'Valid')

# 4. Format the Order Date column as mm-dd-yyyy (leave empty for missing ones)
df_ecommerce['Order Date'] = raw_dates_coerced.dt.strftime('%m-%d-%Y').fillna("")

# 5. Save the full updated dataset back to your file
df_ecommerce.to_csv(csv_path, index=False)

# 6. Handle presentation layer so empty prices stay clean in the interactive viewer
df_display = df_ecommerce.copy()
df_display['Price'] = df_display['Price'].replace("", " ")

# Preview the updated grid structure
df_display[['Order ID', 'Product Name', 'Price', 'Price_Audit_Flag', 'Order Date', 'Date_Audit_Flag']].head(10)

,Order ID,Product Name,Price,Price_Audit_Flag,Order Date,Date_Audit_Flag
0,ORD-10001,Stainless Steel Knife Set,NaN,Unknown,,Unknown
1,ORD-10002,Running Shoes Men,24.64,Valid,12-03-2025,Valid
2,ORD-10003,Portable Phone Charger,44.04,Valid,11-23-2026,Valid
3,ORD-10004,Leather Wallet Men,44.57,Valid,04-05-2026,Valid
4,ORD-10005,Memory Foam Pillow,175.03,Valid,,Unknown
5,ORD-10006,Wireless Mouse,34.29,Valid,04-02-2026,Valid
6,ORD-10007,Wireless Mouse,53.59,Valid,04-08-2025,Valid
7,ORD-10008,Baby Onesie Pack,96.43,Valid,02-22-2025,Valid
8,ORD-10009,Wool Winter Scarf,50.77,Valid,02-25-2025,Valid
9,ORD-10010,Ceramic Coffee Mug Set,80.76,Valid,01-19-2025,Valid

In [14]:
import pandas as pd

# 1. Load your live ecommerce dataset
csv_path = 'Ecommerce-Order-Data-Cleaning-Sample-3-copy-xlsx.csv'
df_ecommerce = pd.read_csv(csv_path)

# 2. Extract numbers, leave missing/invalid cells completely empty ""
def clean_and_empty_price(val):
    if pd.isna(val):
        return ""
    val_str = str(val).strip()
    if val_str == "" or val_str == "-" or val_str.lower() == "nan":
        return ""
    try:
        num = float(val_str)
        return f"{num:.2f}"
    except ValueError:
        return ""

df_ecommerce['Price'] = df_ecommerce['Price'].map(clean_and_empty_price)

# 3. Handle the Price_Audit_Flag to catch Negative, Unknown, and Valid entries
def audit_price_flag(val):
    if val == "":
        return 'Unknown'
    try:
        if float(val) < 0:
            return 'Negative'
        return 'Valid'
    except ValueError:
        return 'Unknown'

df_ecommerce['Price_Audit_Flag'] = df_ecommerce['Price'].map(audit_price_flag)

# 4. Save the full updated dataset back to your file
df_ecommerce.to_csv(csv_path, index=False)

# 5. Force display presentation to leave empty cells completely blank in your notebook view
df_display = df_ecommerce.copy()
df_display['Price'] = df_display['Price'].replace("", " ")

# Preview your updated table layout
df_display[['Order ID', 'Product Name', 'Price', 'Price_Audit_Flag']].head(10)

    Order ID               Product Name   Price Price_Audit_Flag
0  ORD-10001  Stainless Steel Knife Set                  Unknown
1  ORD-10002          Running Shoes Men   24.64            Valid
2  ORD-10003     Portable Phone Charger   44.04            Valid
3  ORD-10004         Leather Wallet Men   44.57            Valid
4  ORD-10005         Memory Foam Pillow  175.03            Valid
5  ORD-10006             Wireless Mouse   34.29            Valid
6  ORD-10007             Wireless Mouse   53.59            Valid
7  ORD-10008           Baby Onesie Pack   96.43            Valid
8  ORD-10009          Wool Winter Scarf   50.77            Valid
9  ORD-10010     Ceramic Coffee Mug Set   80.76            Valid